### ISSUE TITLE
Error in attribute value while running arcilator command

### ISSUE THREAD

**Issue by Stevengre** [circt/arc-tests#3]
I encountered an issue while running the following command on the terminal:

```
make -C rocket run
```
 
The error message I received is as follows:

```
arcilator ../build/rocket-small/rocket.mlir --state-file=.//../build/rocket-small/rocket.json -o .//../build/rocket-small/rocket-arc.ll --mlir-timing --print-debug-info --observe-wires=0 --observe-ports=0 --observe-named-values=0
../build/rocket-small/rocket.mlir:1288:47: error: expected attribute value
          %ASSERT_VERBOSE_COND_ = sv.macro.ref< "ASSERT_VERBOSE_COND_"> : i1
                                              ^
===-------------------------------------------------------------------------===
                         ... Execution time report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 0.0834 seconds

  ----Wall Time----  ----Name----
    0.0815 ( 97.7%)  Parse MLIR input
    0.0019 (  2.3%)  Rest
    0.0834 (100.0%)  Total
make: *** [../build/rocket-small/rocket.json] Error 1
```
 
I would like to submit this issue on GitHub for further assistance and resolution. Thank you so much!

**Comment by fabianschuiki** [comment]
Hey @Stevengre, thanks for reporting the issue! This looks like the `rocket.mlir` input is malformatted. What might have happened is that the syntax for `sv.macro.ref` has changed in CIRCT, but `rocket.mlir` has been generated by an older version of `firtool`.

Try deleting `../build/rocket-small/rocket.mlir` and running `make` again such that you get a fresh copy of it along the way 🙂

**Comment by Stevengre** [comment]
Thank you for your kind assistance! It has successfully resolved my issue.

**Comment by fabianschuiki** [comment]
Great! Happy to hear this worked :-) I'll close this issue as resolved. Feel free to reopen if anything comes up :slightly_smiling_face:
